version: '3.8'
services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: main
        ports:
            - "5433:5432"         
    web:
        build: .
        command: 'python main.py'
        volumes:
            - .:/code
        ports:
            - "8001:5000"
        depends_on:
            - db
    queue:
        build: .
        command: 'python -u consumer.py'
        depends_on:
            - db
